export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  mercadoPagoAccessToken: process.env.MERCADO_PAGO_ACCESS_TOKEN ?? "",
  mercadoPagoUserId: process.env.MERCADO_PAGO_USER_ID ?? "",
  frontendUrl: process.env.VITE_FRONTEND_URL ?? "http://localhost:3000",
  authBypass: process.env.AUTH_BYPASS === "true",
  authBypassPassword: process.env.AUTH_BYPASS_PASSWORD ?? "",
};
